# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\".\n\tOrderItem\x12\x0f\n\x07prod_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\".\n\x0bOrderStatus\x12\x0f\n\x07prod_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\"5\n\x12\x43reateOrderRequest\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.order.OrderItem\"?\n\x13\x43reateOrderResponse\x12(\n\x0citems_status\x18\x01 \x03(\x0b\x32\x12.order.OrderStatus\"&\n\x12\x43\x61ncelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"%\n\x13\x43\x61ncelOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\";\n\x0b\x45ndResponse\x12\x16\n\x0etotal_products\x18\x01 \x01(\x05\x12\x14\n\x0ctotal_orders\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2\xc3\x01\n\x0cOrderService\x12\x44\n\x0b\x43reateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12\x44\n\x0b\x43\x61ncelOrder\x12\x19.order.CancelOrderRequest\x1a\x1a.order.CancelOrderResponse\x12\'\n\x03\x45nd\x12\x0c.order.Empty\x1a\x12.order.EndResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERITEM']._serialized_start=22
  _globals['_ORDERITEM']._serialized_end=68
  _globals['_ORDERSTATUS']._serialized_start=70
  _globals['_ORDERSTATUS']._serialized_end=116
  _globals['_CREATEORDERREQUEST']._serialized_start=118
  _globals['_CREATEORDERREQUEST']._serialized_end=171
  _globals['_CREATEORDERRESPONSE']._serialized_start=173
  _globals['_CREATEORDERRESPONSE']._serialized_end=236
  _globals['_CANCELORDERREQUEST']._serialized_start=238
  _globals['_CANCELORDERREQUEST']._serialized_end=276
  _globals['_CANCELORDERRESPONSE']._serialized_start=278
  _globals['_CANCELORDERRESPONSE']._serialized_end=315
  _globals['_ENDRESPONSE']._serialized_start=317
  _globals['_ENDRESPONSE']._serialized_end=376
  _globals['_EMPTY']._serialized_start=378
  _globals['_EMPTY']._serialized_end=385
  _globals['_ORDERSERVICE']._serialized_start=388
  _globals['_ORDERSERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
