# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x12\x05stock\":\n\x11\x41\x64\x64ProductRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"(\n\x12\x41\x64\x64ProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\":\n\x15\x43hangeQuantityRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"(\n\x16\x43hangeQuantityResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"D\n\x07Product\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"/\n\x0bProductList\x12 \n\x08products\x18\x01 \x03(\x0b\x32\x0e.stock.Product\"&\n\x0c\x45xitResponse\x12\x16\n\x0etotal_products\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xfd\x01\n\x0cStockService\x12\x41\n\nAddProduct\x12\x18.stock.AddProductRequest\x1a\x19.stock.AddProductResponse\x12M\n\x0e\x43hangeQuantity\x12\x1c.stock.ChangeQuantityRequest\x1a\x1d.stock.ChangeQuantityResponse\x12\x30\n\x0cListProducts\x12\x0c.stock.Empty\x1a\x12.stock.ProductList\x12)\n\x04\x45xit\x12\x0c.stock.Empty\x1a\x13.stock.ExitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDPRODUCTREQUEST']._serialized_start=22
  _globals['_ADDPRODUCTREQUEST']._serialized_end=80
  _globals['_ADDPRODUCTRESPONSE']._serialized_start=82
  _globals['_ADDPRODUCTRESPONSE']._serialized_end=122
  _globals['_CHANGEQUANTITYREQUEST']._serialized_start=124
  _globals['_CHANGEQUANTITYREQUEST']._serialized_end=182
  _globals['_CHANGEQUANTITYRESPONSE']._serialized_start=184
  _globals['_CHANGEQUANTITYRESPONSE']._serialized_end=224
  _globals['_PRODUCT']._serialized_start=226
  _globals['_PRODUCT']._serialized_end=294
  _globals['_PRODUCTLIST']._serialized_start=296
  _globals['_PRODUCTLIST']._serialized_end=343
  _globals['_EXITRESPONSE']._serialized_start=345
  _globals['_EXITRESPONSE']._serialized_end=383
  _globals['_EMPTY']._serialized_start=385
  _globals['_EMPTY']._serialized_end=392
  _globals['_STOCKSERVICE']._serialized_start=395
  _globals['_STOCKSERVICE']._serialized_end=648
# @@protoc_insertion_point(module_scope)
